version : '3'
services:

  app:
    build: spring-docker
    ports:
      - ${SPRING_HOST_PORT}:${SPRING_CONTAINER_PORT}
    links:
      - db

  rabbitmq:
    container_name: 'rabbitmq'
    build: rabbitmq
    ports:
      - ${RABBITMQ_HOST_PORT}:${RABBITMQ_CONTAINER_PORT}
      - ${RABBITMQ_MANAGEMENT_HOST_PORT}:${RABBITMQ_MANAGEMENT_CONTAINER_PORT}
    volumes:
      - 'rabbitmq_data:/data'

  db:
    build: redis-docker
    ports:
      - ${REDIS_HOST_PORT}:${REDIS_CONTAINER_PORT}

  sonarqube:
    image: sonarqube:lts
    ports:
      - ${SONARQUBE_HOST_PORT}:${SONARQUBE_CONTAINER_PORT}

volumes:
  rabbitmq_data:
