version : '3'
services:

  nginx:
    build: nginx-docker
    ports:
      - ${NGINX_HOST_PORT}:${NGINX_CONTAINER_PORT}
    depends_on:
      - app_1
      - app_2

  app_1:
    build: spring-docker
    links:
      - db

  app_2:
    build: spring-docker
    links:
      - db

  db:
    image: redis:latest

