version : '3.2'
services:

  db:
    image: redis:latest

  app:
    image: yap_app
    depends_on:
      - db

  nginx:
    image: yap_nginx
    ports:
      - target: 80
        published: 80
        mode: host
    depends_on:
      - app




