version: "3.7"

services:

  db:
    image: redis:latest
    ports:
      - mode: host
        target: 6379
        published: 6379

  urlsqrs:
    image: yap_urlsqrs
    depends_on:
      - db

  csvsmaster:
    image: yap_csvsmaster
    depends_on:
      - db
      - rabbitmq

  csvsworker:
    image: yap_csvsworker
    depends_on:
      - db
      - rabbitmq

  python:
    image: yap_python
    volumes:
      - ./frontend:/app

  nginx:
    image: yap_nginx
    ports:
      - target: 80
        published: 80
        mode: host
    depends_on:
      - app

  rabbitmq:
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    ports:
      - target: 15672
        published: 15672
        mode: host

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - target: 9090
        published: 9090
        mode: host

  grafana:
    image: grafana/grafana
    volumes:
      - ./grafana-data:/var/lib/grafana
    ports:
      - target: 3000
        published: 3000
        mode: host
