version: "3.7"

services:

  db:
    image: redis:latest

  app:
    image: yap_app
    depends_on:
      - db

  python:
    image: yap_python
    volumes:
      - ./frontend:/app

  nginx:
    image: yap_nginx
    ports:
      - target: 80
        published: 80
        mode: host
    depends_on:
      - app

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - target: 9090
        published: 9090
        mode: host

  grafana:
    image: grafana/grafana
    volumes:
      - ./grafana-data:/var/lib/grafana
    ports:
      - target: 3000
        published: 3000
        mode: host
