
scrape_configs:

  - job_name: 'SPRING'
    scrape_interval: 1s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['yap_nginx:80']

  - job_name: 'PROMETHEUS'
    scrape_interval: 1s
    static_configs:
      - targets: ['localhost:9090']
