{
 "title": "Yap Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "JVM Live Threads (Spring Actuator)",
   "type": "graph",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_threads_live_threads" }
   ]
  },
  {
   "title": "System Load Average (Spring Actuator)",
   "type": "graph",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "system_load_average_1m" }
   ]
  },
  {
   "title": "System CPU Usage (Spring Actuator)",
   "type": "graph",
   "gridPos": { "h": 23, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "system_cpu_usage" }
   ]
  },
  {
   "title": "HTTP REQUESTS",
   "type": "graph",
   "gridPos": { "h": 23, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_count"
    }
   ]
  }
 ]
}