name: CI

on: [push]

jobs:
  build:
    name: CI
    runs-on: ${{ matrix.os }}
    matrix:
      os: [ ubuntu-20.04, ubuntu-18.04, ubuntu-16.04, macos-10.15, windows-2019 ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: eskatos/gradle-command-action@v1
        with:
            arguments: build
